# top
seed: 0
pilot: false
local_data_folder: ./data
wandb_project_name: draftrec
exp_name: test
dataset_type: lol
model_type: draftrec
# dataloader
train_dataloader_type: match
val_dataloader_type: match
test_dataloader_type: match
train_batch_size: 128
val_batch_size: 128
test_batch_size: 128
max_seq_len: 50
num_special_tokens: 4
num_turns: 10
num_champions: null
num_roles: null
num_teams: null
num_outcomes: null
num_stats: null
num_users: null
num_negatives: 128
window_size: 100
# trainer
trainer_type: match
device: mps
use_parallel: true
num_workers: 4  # larger number of workers induce higher i/o bottleneck
# optimizer
optimizer: sgd
lr: 0.01
weight_decay: 0.00001
momentum: 0.9
lmbda: 0.1
clip_grad_norm: 5
dropout: 0.1
# epochs
num_epochs: 10
# evaluation
metric_ks:
- 1
- 5
- 10
- 20
best_metric: ACC
# model
model_init_seed: 0
hidden_units: 128
num_blocks: 2
head_type: dot
num_heads: 2
num_hidden_layers: null
min_prob: null
gradient_accumulation_steps: 2